// Generates src/brands/brands.generated.ts from the Simple Icons package (CC0-1.0).
// Run with `npm run gen:brands` after adding a brand to CURATED or updating simple-icons.
// Nintendo and Xbox marks are not in Simple Icons (removed at their owners' request) and are deliberately not sourced elsewhere.
import { writeFileSync, readFileSync } from 'node:fs';
import * as si from 'simple-icons';
import { svgPathBbox } from 'svg-path-bbox';

const CURATED = [
  // [slug, label, category]
  ['steam', 'Steam', 'store'],
  ['epicgames', 'Epic Games', 'store'],
  ['gogdotcom', 'GOG', 'store'],
  ['itchdotio', 'itch.io', 'store'],
  ['humblebundle', 'Humble Bundle', 'store'],
  ['ubisoft', 'Ubisoft', 'store'],
  ['ea', 'EA', 'store'],
  ['battledotnet', 'Battle.net', 'store'],
  ['googleplay', 'Google Play', 'store'],
  ['appstore', 'App Store', 'store'],
  ['playstation', 'PlayStation', 'platform'],
  ['playstation2', 'PlayStation 2', 'platform'],
  ['playstation3', 'PlayStation 3', 'platform'],
  ['playstation4', 'PlayStation 4', 'platform'],
  ['playstation5', 'PlayStation 5', 'platform'],
  ['playstationportable', 'PSP', 'platform'],
  ['playstationvita', 'PS Vita', 'platform'],
  ['steamdeck', 'Steam Deck', 'platform'],
  ['sega', 'Sega', 'platform'],
  ['atari', 'Atari', 'platform'],
];

const bySlug = Object.fromEntries(Object.values(si).filter((v) => v && v.slug).map((v) => [v.slug, v]));
const version = JSON.parse(readFileSync(new URL('../node_modules/simple-icons/package.json', import.meta.url), 'utf8')).version;

const brands = CURATED.map(([slug, label, category]) => {
  const icon = bySlug[slug];
  if (!icon) throw new Error(`"${slug}" is not in simple-icons@${version}; remove it from CURATED`);
  const [x0, y0, x1, y1] = svgPathBbox(icon.path).map((n) => Math.round(n * 1000) / 1000);
  return { id: slug, label, category, path: icon.path, hex: icon.hex, bbox: [x0, y0, x1, y1], ...(icon.guidelines && { guidelines: icon.guidelines }) };
});

const out = `// GENERATED by scripts/gen-brands.mjs from simple-icons@${version} (CC0-1.0). Do not edit by hand.
// The marks are trademarks of their respective owners; see THIRD_PARTY_NOTICES.md.
import type { Brand } from './types';

export const BRANDS: Brand[] = ${JSON.stringify(brands, null, 2)};
`;
writeFileSync(new URL('../src/brands/brands.generated.ts', import.meta.url), out);
console.log(`Wrote ${brands.length} brands from simple-icons@${version}`);
